#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo "Start: run Django Migrations"
python manage.py migrate
echo "Start: run Django Server"
{%- if cookiecutter.use_django_extensions == 'y' %}
exec python manage.py runserver_plus 0.0.0.0:8000
{%- else %}
exec python manage.py runserver 0.0.0.0:8000
{%- endif %}